# Generated by Django 4.1.1 on 2024-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='komyuniti-event-image'),
        ),
    ]
