# Generated by Django 4.1.1 on 2024-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='image',
            field=models.FileField(default='komyuniti-post-image/avatar_mclyfi.jpg', null=True, upload_to='komyuniti-group-image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='komyuniti-post-image/avatar_mclyfi.jpg', null=True, upload_to='komyuniti-user-image'),
        ),
    ]
