# Generated by Django 4.1.1 on 2024-03-31 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_groups_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='invite_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_request',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
