# Generated by Django 4.1.1 on 2024-04-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_request_invite_request_user_request_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
