# Generated by Django 4.1.1 on 2024-04-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='desciption',
            field=models.TextField(null=True),
        ),
    ]
