# Generated by Django 4.1.1 on 2024-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_club_description_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.FileField(blank=True, default='komyuniti-post-image/avatar_mclyfi.jpg', null=True, upload_to='komyuniti-group-image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='komyuniti-post-image/avatar_mclyfi.jpg', null=True, upload_to='komyuniti-user-image'),
        ),
    ]
