# Generated by Django 4.1.1 on 2024-04-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='base.tags'),
        ),
    ]
