# Generated by Django 5.0.4 on 2024-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_groups_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
