# Generated by Django 5.0.4 on 2024-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_club_options_club_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='club_join_request',
            field=models.BooleanField(default=False),
        ),
    ]
