# Generated by Django 5.0.4 on 2024-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_user_request_club_join_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
