# Generated by Django 5.0.4 on 2024-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.FileField(blank=True, default='komyuniti-post-image/avatar_mclyfi.jpg', null=True, upload_to='komyuniti-club-image'),
        ),
    ]
