# Generated by Django 5.0.4 on 2024-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_post',
            name='embed',
            field=models.URLField(blank=True, null=True),
        ),
    ]
