# Generated by Django 5.0.4 on 2024-04-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_club_post_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed',
            field=models.URLField(blank=True, null=True),
        ),
    ]
