# Generated by Django 5.0.4 on 2024-04-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_post_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='club_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_postr_comment', to='base.club_post'),
        ),
    ]
