# Generated by Django 5.0.4 on 2024-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_comments_club_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_post',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
