# Generated by Django 5.0.4 on 2024-04-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_user_request_club_alter_user_request_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
