# Generated by Django 5.0.4 on 2024-05-16 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_comments_options_alter_club_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='club_post',
        ),
        migrations.CreateModel(
            name='Club_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_comment_post', to='base.club_post')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
