# Generated by Django 5.0.4 on 2024-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_comments_options_remove_comments_club_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_post',
            name='post_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
