# Generated by Django 5.0.4 on 2024-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_club_post_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
