# Generated by Django 5.0.4 on 2024-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_post_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='theme',
            field=models.CharField(choices=[('#d8dee9', 'Snow'), ('#f9d1d1', 'Pale Pink'), ('#b8dad9', 'Scandal'), ('#ffe5f1', 'Lavender Blush'), ('#ffd3d6', 'Misty Rose')], default='#f8f9fa', max_length=7),
        ),
    ]
