# Generated by Django 5.0.4 on 2024-05-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_groups_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='theme',
            field=models.CharField(choices=[('#d8dee9', 'Snow'), ('#f9d1d1', 'Pale Pink'), ('#b8dad9', 'Scandal'), ('#ffe5f1', 'Lavender Blush'), ('#ffd3d6', 'Misty Rose'), ('#fcf1c0', 'Oasis'), ('#f6acc5', 'Cupid'), ('#c79274', 'Fallow'), ('#ffe0dl', 'Blanched Almond')], default='#f8f9fa', max_length=7),
        ),
    ]
