# Generated by Django 5.0.4 on 2024-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_groups_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='theme',
            field=models.CharField(choices=[('#d8dee9', 'Snow'), ('#f9d1d1', 'Pale Pink'), ('#b8dad9', 'Scandal'), ('#ffe5f1', 'Lavender Blush'), ('#ffd3d6', 'Misty Rose'), ('#ADDFFF', 'Light Day Blue'), ('#F0FFF0', 'HoneyDew'), ('#FFFFCC', 'Cream'), ('#E5E4E2', 'Platinum'), ('#fcf1c0', 'Oasis'), ('#C3FDB8', 'Light Jade'), ('#C8C4DF', 'Viola'), ('#ffe0d1', 'Blanched Almond'), ('#F1E5AC', 'Light Gold')], default='#f8f9fa', max_length=7),
        ),
    ]
