# Generated by Django 4.2 on 2025-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_user_request_club_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_post',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
