# Generated by Django 4.2 on 2025-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_club_post_cloudinary_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
